---
name: TVHeadend
version: 0.0.2
slug: tvheadend
description: TV streaming server and recorder with O2 web server
url: "https://github.com/jaroslavhykel/addon-tvheadend/tree/main/tvheadend"
init: false
panel_icon: mdi:television
arch:
  - aarch64
host_network: true
webui: "http://[HOST]:[PORT:9981]/"
usb: true
udev: true
homeassistant_api: true
hassio_api: true
hassio_role: manager
stdin: true
ports_description:
  9981/tcp: TVH Web Interface
  9982/tcp: TVH HTSP
map:
  - config:rw
  - share:rw
  - media:rw
options:
  o2_username: ""
  o2_password: ""
  o2_deviceid: "Android_15"
  o2_webserver_ip: "127.0.0.1"
  system_packages: []
  init_commands: []
  args: ""
schema:
  o2_username:
    - str?
  o2_password:
    - str?
  o2_deviceid:
    - str?
  o2_webserver_ip:
    - str?
  system_packages:
    - str?
  init_commands:
    - str?
  args: str?
